name: Static code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/setup-java@v3.11.0
      with:
        java-version: 11
        distribution: temurin
    - uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.24.3'
        cache: true

    - name: Install dependencies for super_tooltip
      run: flutter pub get

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
